version: '3.8'

services:
  # Main WhatsApp Bot application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./sessions:/app/sessions
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./logs:/app/logs
    depends_on:
      - redis
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/whatsapp-bot
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WHATSAPP_SESSION_PATH=/app/sessions
      - JWT_SECRET=replace_with_secure_token
      - RATE_LIMIT_WINDOW=15
      - RATE_LIMIT_MAX_REQUESTS=100
    networks:
      - whatsapp-bot-network

  # Redis for queue management
  redis:
    image: redis:7-alpine
    container_name: whatsapp-bot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory-policy noeviction
    networks:
      - whatsapp-bot-network

  # MongoDB for data storage
  mongo:
    image: mongo:6
    container_name: whatsapp-bot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - whatsapp-bot-network

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: whatsapp-bot-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - whatsapp-bot-network

  # Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    container_name: whatsapp-bot-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin_password_change_me
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - whatsapp-bot-network

  # NGINX reverse proxy for secure access
  nginx:
    image: nginx:alpine
    container_name: whatsapp-bot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - app
      - grafana
    networks:
      - whatsapp-bot-network

volumes:
  redis-data:
  mongo-data:
  prometheus-data:
  grafana-data:

networks:
  whatsapp-bot-network:
    driver: bridge 