module.exports = [
  { name: "Delhi Public School-Navi Mumbai", city: "Navi Mumbai", aliases: ["DPS Navi Mumbai", "Delhi Public School Navi Mumbai"] },
  { name: "Sadhu Vaswani International School-Mumbai", city: "Mumbai", aliases: ["Sadhu Vaswani Mumbai", "SVIS Mumbai"] },
  { name: "Bombay Cambridge School, Andheri West", city: "Mumbai", aliases: ["Bombay Cambridge Andheri"] },
  { name: "Greater Valley International school Mumbai", city: "Mumbai", aliases: ["Greater Valley International Mumbai"] },
  { name: "SS Nikam English School Mangaon, Raigad", city: "Mangaon, Raigad", aliases: ["SS Nikam Mangaon"] },
  { name: "Savitridevi Hariram Agarwal International School, Kandivali", city: "Kandivali", aliases: ["Savitridevi Agarwal Kandivali"] },
  { name: "Kashinath Palod School, Jalgaon", city: "Jalgaon", aliases: ["Kashinath Palod Jalgaon"] },
  { name: "Infant Jesus English Public High School Rajura", city: "Rajura", aliases: ["Infant Jesus Rajura"] },
  { name: "Our Lady of Salvation High School Dadar", city: "Dadar", aliases: ["Salvation High Dadar"] },
  { name: "Indira National School", city: "Unknown City", aliases: [] },
  { name: "Vidyarammbh School", city: "Unknown City", aliases: [] },
  { name: "PSBA School", city: "Unknown City", aliases: [] },
  { name: "Bonsala Militray School,Nashik", city: "Nashik", aliases: ["Bonsala Nashik"] },
  { name: "Dr. Pillai Global School, Gorai", city: "Gorai", aliases: ["Pillai Global Gorai"] },
  { name: "Juhulelal Trust School, Ulhasnagar", city: "Ulhasnagar", aliases: ["Juhulelal Ulhasnagar"] },
  { name: "Muljibhai Mehta International School, Virar", city: "Virar", aliases: ["Muljibhai Mehta Virar"] },
  { name: "Apeejay School", city: "Unknown City", aliases: [] },
  { name: "Apeejay School", city: "Unknown City", aliases: [] },
  { name: "Kesarimal Nagar Vidyalaya", city: "Unknown City", aliases: [] },
  { name: "School of Scholars", city: "Unknown City", aliases: [] },
  { name: "Shri Chhatrapati Shivaji Vidyalaya", city: "Unknown City", aliases: ["Chhatrapati Shivaji Vidyalaya"] },
  { name: "VISHWANATH SECONDARY AND HIGHER SEC VIDYALAYA", city: "Unknown City", aliases: ["Vishwanath Vidyalaya"] },
  { name: "Bhagini Nivedita Kanya Vidyalaya", city: "Unknown City", aliases: ["Bhagini Nivedita Vidyalaya"] },
  { name: "Siemens School, Aurangabad", city: "Aurangabad", aliases: ["Siemens Aurangabad"] },
  { name: "New English School and Jr. College", city: "Unknown City", aliases: ["New English Jr College"] },
  { name: "ANNAJI GOVINDRAO PAWAR( SAWKAR) VIDHYALAYA VAHAGAON", city: "Vahagaon", aliases: ["Annaji Govindrao Pawar Vahagaon"] },
  { name: "Maharaja Shivaji High School and Junior College", city: "Unknown City", aliases: ["Maharaja Shivaji High School"] },
  { name: "Army Public School, Mumbai", city: "Mumbai", aliases: ["Army Public Mumbai"] },
  { name: "Mansukhbhai Kothari National Public School,Kondhwa", city: "Kondhwa", aliases: ["Kothari National Kondhwa"] },
  { name: "Golden Jubilee School", city: "Unknown City", aliases: [] },
  { name: "K.M.S. Dr Shirodkar High School", city: "Unknown City", aliases: ["Shirodkar High School"] },
  { name: "Shri Sant Savta Gurukul Madhyamik vidyalaya", city: "Unknown City", aliases: ["Sant Savta Gurukul"] },
  { name: "Janpeer Vidyalaya Nalwandi Beed Maharashtra", city: "Nalwandi, Beed", aliases: ["Janpeer Nalwandi"] },
  { name: "Kothari International School  Pune", city: "Pune", aliases: ["Kothari International Pune"] },
  { name: "JBCN International School Borivalli", city: "Borivalli", aliases: ["JBCN Borivalli"] },
  { name: "JBCN International School , Chembur", city: "Chembur", aliases: ["JBCN Chembur"] },
  { name: "JBCN International School, Oshiwara Mumbai", city: "Oshiwara, Mumbai", aliases: ["JBCN Oshiwara"] },
  { name: "Kids Kingdom Academy", city: "Unknown City", aliases: [] },
  { name: "Shree VS Gurukul, Ghatkopar", city: "Ghatkopar", aliases: ["VS Gurukul Ghatkopar"] },
  { name: "Loknete Dinkar Aba Patil Secondary Vidyalay, Kumathe Sangli", city: "Kumathe, Sangli", aliases: ["Loknete Dinkar Aba Patil Kumathe Sangli"] }
]; 